# Generated by Django 2.2.4 on 2019-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Ingresa tu nombre', max_length=25)),
                ('Apellido', models.CharField(help_text='ingresa tu apellido', max_length=25)),
                ('colonia', models.CharField(help_text='ingresa tu colona', max_length=45)),
                ('E_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
